EXTRA_CFLAGS := -I$(M)/include \
	-DCONFIG_IP_SET_MAX=$(IP_SET_MAX)

obj-m += ip_set.o
#ipt_set.o ipt_SET.o
obj-m += ip_set_bitmap_ip.o ip_set_bitmap_ipmac.o ip_set_bitmap_port.o
obj-m += ip_set_hash_ip.o
#obj-m += ip_set_iphash.o ip_set_nethash.o ip_set_ipporthash.o
#obj-m += ip_set_ipportiphash.o ip_set_ipportnethash.o
#obj-m += ip_set_iptree.o ip_set_iptreemap.o
#obj-m += ip_set_setlist.o

# It's for me...
incdirs := $(M) $(M)/include/linux/netfilter
clean-files := $(foreach dir,$(incdirs),$(wildcard $(dir)/*~))
