EXTRA_CFLAGS := -I$(M)/include \
	-DCONFIG_IP_SET_MAX=$(IP_SET_MAX) \
	-DNETLINK_DUMP_CONST=$(NETLINK_DUMP_CONST) \
	-DNFNL_CB_CONST=$(NFNL_CB_CONST)

obj-m += ip_set.o xt_set.o
obj-m += ip_set_bitmap_ip.o ip_set_bitmap_ipmac.o ip_set_bitmap_port.o
obj-m += ip_set_hash_ip.o ip_set_hash_ipport.o ip_set_hash_ipportip.o
obj-m += ip_set_hash_net.o ip_set_hash_ipportnet.o
obj-m += ip_set_list_set.o

# It's for me...
incdirs := $(M) $(M)/include/linux/netfilter
clean-files := $(foreach dir,$(incdirs),$(wildcard $(dir)/*~))
