NOSTDINC_FLAGS += -I$(M)/include
EXTRA_CFLAGS := -DCONFIG_IP_SET_MAX=$(IP_SET_MAX)

ip_set-y := ip_set_core.o pfxlen.o
obj-m += ip_set.o xt_set.o
obj-m += ip_set_bitmap_ip.o ip_set_bitmap_ipmac.o ip_set_bitmap_port.o
obj-m += ip_set_hash_ip.o ip_set_hash_ipport.o ip_set_hash_ipportip.o
obj-m += ip_set_hash_net.o ip_set_hash_ipportnet.o ip_set_hash_netport.o
obj-m += ip_set_list_set.o

# It's for me...
incdirs := $(M) $(M)/include/linux/netfilter $(M)/include/linux/netfilter/ipset
clean-files := $(foreach dir,$(incdirs),$(wildcard $(dir)/*~))
